# -*- coding: utf-8 -*-
"""
/***************************************************************************
 POLO
                                 A QGIS plugin
 Elabora automaticamente relátorios e mapas de focos de calor a partir do bando de dados FIRMS/NASA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-29
        copyright            : (C) 2021 by Newton Coelho Monteiro
        email                : newtongel@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load POLO class from file POLO.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .POLO import POLO
    return POLO(iface)
